### ISSUE TITLE
aws provider

### ISSUE THREAD

**Issue by FernandoMiguel** [ActionIQ/terraform-aws-retool-ecs-fargate#13]
why is there a provider in this module?
there is no alias to, and no resources seem to be using it.
Providers should be defined only in the root module, not in the modules, as per hashicorp standard practices

**Comment by OldCrowEW** [comment]
👋  @FernandoMiguel Could you point to the HashiCorp standard practices you are referring to? The best I could find was here: https://developer.hashicorp.com/terraform/language/modules/develop/providers
> A module intended to be called by one or more other modules must not contain any provider blocks

When designing this module, there was no intention of calling the module from another. We'd be happy to consider a feature request if desired.

**Comment by FernandoMiguel** [comment]
That's the correct recommendation.
When you share this code base, one would assume you wished for others to benefit from your work and use it as a reusable module.

That's what we (tried to) do.
Sadly this implementation prevents us from accessing aws correct account and left us with forking this until this module is improved.

Thanks for your great work.

**Comment by OldCrowEW** [comment]
hey @FernandoMiguel can you help me here? What I linked says what we did was correct since we did not plan to call it from another module. Are you requesting a feature/improvement? I'm not reading a request in your responses.

**Comment by FernandoMiguel** [comment]
Ideally it would be helpful if this behaved as a shared module so others can encapsulate it in their code.
As you stated, this current implementation only works with this as a root module, which isn't really sharable.
We can jump on a call tomorrow if you would like to discuss further.

Thanks.

**Comment by OldCrowEW** [comment]
> Ideally it would be helpful if this behaved as a shared module so others can encapsulate it in their code. As you stated, this current implementation only works with this as a root module, which isn't really sharable. We can jump on a call tomorrow if you would like to discuss further.
> 
> Thanks.

Hey @FernandoMiguel I pulled the provider as asked. Hope this helps!

**Comment by FernandoMiguel** [comment]
thanks. i'll pass this along to our dev team using this module
